version: '3.8'

services:
  frontend:
    build: ./example-frontend/
    ports:
      - 5000:5000
  
  backend:
    build: ./example-backend/
    ports:
      - 8080:8080
    environment:
      REQUEST_ORIGIN: 'http://localhost:5000'
      REDIS_HOST: 'redis'
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres_db
    volumes:
      - database:/var/lib/postgres/data

  redis:
    image: redis:latest
    command: redis-server --loglevel warning

volumes:
  database:
