version: '3.8'

services:
  frontend:
    build: ./example-frontend/
    ports:
      - 5000:5000
  
  backend:
    build: ./example-backend/
    ports:
      - 8080:8080
    environment:
      REQUEST_ORIGIN: 'http://localhost:5000'
      REDIS_HOST: 'database'

  database:
    image: redis:latest
    command: redis-server --loglevel warning
