version: '3.8'

services:
  coursepage:
    image: kornea/coursepage
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursepage

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
