version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/*****/git/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
     - frontend
     - backend

  frontend:
    container_name: frontend
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
   #ports:
   #  - 5000:5000
  
  backend:
    container_name: backend
    build: 
      context: ./example-backend
      dockerfile: Dockerfile
   #ports:
   #  - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: /home/*****/git/database
        target: /var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --loglevel warning

